export default {
  LOG_IN_USER_SUCCESS: 'LOG_IN_USER_SUCCESS',
  LOG_IN_USER_FAILURE: 'LOG_IN_USER_FAILURE',
  LOG_OUT_USER: 'LOG_OUT_USER',
  FETCHED_DOCUMENTS: 'FETCHED_DOCUMENTS',
  FETCHED_CATEGORIES: 'FFETCHED_CATEGORIES'
};

